export const chartData = [
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 1,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 2,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 3,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 4,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 5,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 6,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 7,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 8,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 9,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 10,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 11,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 12,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 13,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 14,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 15,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 16,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 17,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 18,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 19,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 20,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 21,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 22,
  },
  {
    createdAt: "0",
    totalSteps: 0,
    rumination: 0,
    threshold: 25,
    ruminationTimeInMinutes: 0,
    ruminationTimeInHours:0,
    temperature: 0,
    heartBeat: 0,
    hour: 23,
  },
];

export const stepByDay = [
  { xAxis: "20/12/23", dataValue: 2200 },
  { xAxis: "21/12/23", dataValue: 3200 },
  { xAxis: "22/12/23", dataValue: 1200 },
  { xAxis: "23/12/23", dataValue: 2500 },
  { xAxis: "24/12/23", dataValue: 2800 },
  { xAxis: "25/12/23", dataValue: 3500 },
  { xAxis: "26/12/23", dataValue: 2000 },
];

export const totalStepsFakeData = [
  { xAxis: "0-1 AM", dataValue: 120 },
  { xAxis: "1-2 AM", dataValue: 80 },
  { xAxis: "2-3 AM", dataValue: 0 },
  { xAxis: "3-4 AM", dataValue: 60 },
  { xAxis: "4-5 AM", dataValue: 0 },
  { xAxis: "5-6 AM", dataValue: 100 },
  { xAxis: "6-7 AM", dataValue: 90 },
  { xAxis: "7-8 AM", dataValue: 70 },
  { xAxis: "8-9 AM", dataValue: 0 },
  { xAxis: "9-10 AM", dataValue: 130 },
  { xAxis: "10-11 AM", dataValue: 0 },
  { xAxis: "11-12 AM", dataValue: 110 },
  { xAxis: "12-1 PM", dataValue: 0 },
  { xAxis: "1-2 PM", dataValue: 80 },
  { xAxis: "2-3 PM", dataValue: 0 },
  { xAxis: "3-4 PM", dataValue: 70 },
  { xAxis: "4-5 PM", dataValue: 0 },
  { xAxis: "5-6 PM", dataValue: 100 },
  { xAxis: "6-7 PM", dataValue: 0 },
  { xAxis: "7-8 PM", dataValue: 90 },
  { xAxis: "8-9 PM", dataValue: 0 },
  { xAxis: "9-10 PM", dataValue: 120 },
  { xAxis: "10-11 PM", dataValue: 60 },
  { xAxis: "11-12 PM", dataValue: 60 },
];

export const activityDayWise = [
  { xAxis: "20/12/23", dataValue: 2200 },
  { xAxis: "21/12/23", dataValue: 3200 },
  { xAxis: "22/12/23", dataValue: 1200 },
  { xAxis: "23/12/23", dataValue: 2500 },
  { xAxis: "24/12/23", dataValue: 2800 },
  { xAxis: "25/12/23", dataValue: 3500 },
  { xAxis: "26/12/23", dataValue: 2000 },
];

export const activityFakeData = [
  { xAxis: "00:00", dataValue: 10 },
  { xAxis: "01:00", dataValue: 15 },
  { xAxis: "02:00", dataValue: 5 },
  { xAxis: "03:00", dataValue: 8 },
  { xAxis: "04:00", dataValue: 12 },
  { xAxis: "05:00", dataValue: 18 },
  { xAxis: "06:00", dataValue: 6 },
  { xAxis: "07:00", dataValue: 11 },
  { xAxis: "08:00", dataValue: 14 },
  { xAxis: "09:00", dataValue: 9 },
  { xAxis: "10:00", dataValue: 16 },
  { xAxis: "11:00", dataValue: 7 },
  { xAxis: "12:00", dataValue: 13 },
  { xAxis: "13:00", dataValue: 10 },
  { xAxis: "14:00", dataValue: 19 },
  { xAxis: "15:00", dataValue: 8 },
  { xAxis: "16:00", dataValue: 12 },
  { xAxis: "17:00", dataValue: 17 },
  { xAxis: "18:00", dataValue: 6 },
  { xAxis: "19:00", dataValue: 11 },
  { xAxis: "20:00", dataValue: 15 },
  { xAxis: "21:00", dataValue: 14 },
  { xAxis: "22:00", dataValue: 10 },
  { xAxis: "23:00", dataValue: 8 },
];

export const ruminationf0 = [
  { xAxis: "0-2 AM", dataValue: 75 },
  { xAxis: "2-4 AM", dataValue: 20 },
  { xAxis: "4-6 AM", dataValue: 35 },
  { xAxis: "6-8 AM", dataValue: 65 },
  { xAxis: "8-10 AM", dataValue: 50 },
  { xAxis: "10-12 AM", dataValue: 42 },
  { xAxis: "12-2 PM", dataValue: 30 },
  { xAxis: "2-4 PM", dataValue: 25 },
  { xAxis: "4-6 PM", dataValue: 40 },
  { xAxis: "6-8 PM", dataValue: 35 },
  { xAxis: "8-10 PM", dataValue: 45 },
  { xAxis: "10-12 PM", dataValue: 20 },
];

export const ruminationD0ise = [
  { xAxis: "20/12/23", dataValue: 2200 },
  { xAxis: "21/12/23", dataValue: 3200 },
  { xAxis: "22/12/23", dataValue: 1200 },
  { xAxis: "23/12/23", dataValue: 2500 },
  { xAxis: "24/12/23", dataValue: 2800 },
  { xAxis: "25/12/23", dataValue: 3500 },
  { xAxis: "26/12/23", dataValue: 2000 },
];
